@startuml
|Администратор|
start
:Открытие раздела статистики;

|Система|
:Загрузка данных о продажах;
:Загрузка данных об активности;

|Администратор|
:Выбор временного периода;

|Система|
:Обновление статистики;

|Администратор|
:Просмотр отчетов;

|Администратор|
:Запрос экспорта отчета;

|Система|
:Формирование отчета;
:Выгрузка отчета;

stop
@enduml
