@startuml
|Фазы|
|Администратор|
start
:Администратор нажимает\nкнопку "Выход";

|Система|
:Система завершает\nсессию администратора;

|Система|
:Система перенаправляет\nна страницу входа;

|Система|
:Система подтверждает\nуспешный выход;

stop
@enduml
