@startuml
|Фазы|
|Пользователь|
start
:Пользователь открывает\nформу регистрации;

|Система|
:Система отображает\nформу регистрации;

|Пользователь|
:Пользователь вводит\nemail и пароль;

|Система|
:Система проверяет\nуникальность email;

|Система|
if (Email уникален?) then (да)
  :Система создает\nучетную запись;
  :Система отправляет\nподтверждение на email;
  :Система уведомляет\nоб успешной регистрации;
else (нет)
  :Система выводит\nсообщение об ошибке;
  stop
endif

stop
@enduml
