@startuml
|Фазы|
|Администратор|
start
:Администратор открывает\nраздел статистики;

|Система|
:Система загружает\nданные о продажах;

|Система|
:Система загружает\nданные об активности;

|Администратор|
:Администратор выбирает\nвременной период;

|Система|
:Система обновляет\nстатистику;

|Администратор|
:Администратор просматривает\nотчеты;

|Администратор|
:Администратор запрашивает\nэкспорт отчета;

|Система|
:Система формирует\nи выгружает отчет;

stop
@enduml
