@startuml
|Администратор|
start
:Открытие раздела каталога;

|Система|
:Загрузка списка товаров;

|Администратор|
:Просмотр товаров;

|Администратор|
:Применение фильтров;

|Система|
:Обновление списка товаров;

|Администратор|
:Просмотр отфильтрованных товаров;

stop
@enduml
