@startuml
|Фазы|
|Пользователь|
start
:Пользователь нажимает\n"Оформить заказ";

|Система|
:Система проверяет\nналичие товаров;

|Пользователь|
:Пользователь вводит\nадрес доставки;

|Система|
:Система проверяет\nкорректность адреса;

|Пользователь|
:Пользователь выбирает\nспособ оплаты;

|Система|
:Система создает заказ;

|Система|
:Система отправляет\nподтверждение на email;

|Система|
:Система уведомляет об\nуспешном оформлении;

stop
@enduml
