@startuml
|Фазы|
|Администратор|
start
:Администратор переходит\nна окно;

|Система|
:Система открывает окно\nдля авторизации;

|Администратор|
:Администратор вводит\nлогин или телефон и\nпароль;

|Администратор|
:Администратор нажимает\nкнопку "авторизоваться";

|Система|
:Система выполняет\nпроверку данных и\nавторизует администратора;

|Система|
:Администратор переходит\nв главное окно;

stop
@enduml
