@startuml
|Фазы|
|Пользователь|
start
:Пользователь выбирает\nтовар;

|Система|
:Система добавляет\nтовар в корзину;

|Пользователь|
:Пользователь просматривает\nкорзину;

|Система|
:Система отображает\nсодержимое корзины;

|Пользователь|
:Пользователь изменяет\nколичество товаров;

|Система|
:Система пересчитывает\nстоимость;

|Система|
:Система обновляет\nкорзину;

|Пользователь|
:Пользователь просматривает\nобновленную корзину;

stop
@enduml
