@startuml
|Пользователь|
start
:Пользователь переходит на окно;

|Система|
:Система открывает окно для авторизации;

|Пользователь|
:Пользователь вводит данные для авторизации;

|Пользователь|
:Пользователь нажимает кнопку "авторизоваться";

|Система|
:Система выполняет проверку данных;

|Система|
:Авторизация пользователя;

|Система|
:Переход в главное меню;

stop
@enduml
