@startuml
|Фазы|
|Администратор|
start
:Администратор открывает\nраздел управления заказами;

|Система|
:Система отображает\nсписок всех заказов;

|Администратор|
:Администратор выбирает\nзаказ;

|Система|
:Система отображает\nдетали заказа;

|Администратор|
:Администратор изменяет\nстатус заказа;

|Система|
:Система обновляет\nстатус заказа;

|Система|
:Система подтверждает\nизменение статуса;

stop
@enduml
