@startuml
|Пользователь|
start
:Выбор товара;

|Система|
:Добавление товара в корзину;

|Пользователь|
:Просмотр корзины;

|Система|
:Отображение содержимого корзины;

|Пользователь|
:Изменение количества товаров;

|Система|
:Пересчет стоимости;
:Обновление корзины;

|Пользователь|
:Просмотр обновленной корзины;

stop
@enduml
