@startuml
|Пользователь|
start
:Пользователь переходит на окно;

|Система|
:Система открывает окно для регистрации;

|Пользователь|
:Пользователь вводит данные для регистрации;

|Пользователь|
:Пользователь нажимает кнопку "зарегистрироваться";

|Система|
:Система выполняет проверку данных и регистрирует пользователя;

|Система|
:Пользователь переходит к окну авторизации;

stop
@enduml
