@startuml
|Фазы|
|Пользователь|
start
:Пользователь переходит\nна окно;

|Система|
:Система открывает окно\nдля авторизации;

|Пользователь|
:Пользователь вводит\nлогин или телефон и\nпароль;

|Пользователь|
:Пользователь нажимает\nкнопку "авторизоваться";

|Система|
:Система выполняет\nпроверку данных и\nавторизует пользователя;

|Система|
:Пользователь переходит\nв главное окно;

stop
@enduml
