@startuml
|Фазы|
|Администратор|
start
:Администратор открывает\nраздел каталога;

|Система|
:Система отображает\nсписок всех товаров;

|Администратор|
:Администратор просматривает\nинформацию о товарах;

|Администратор|
:Администратор применяет\nфильтры;

|Система|
:Система обновляет\nсписок товаров;

|Администратор|
:Администратор просматривает\nотфильтрованные товары;

stop
@enduml
