@startuml
|Пользователь|
start
:Открытие каталога товаров;

|Система|
:Загрузка списка товаров;

|Пользователь|
:Просмотр каталога;

|Пользователь|
:Применение фильтров;

|Система|
:Обновление списка товаров;

|Пользователь|
:Выбор товара;

|Система|
:Отображение детальной информации;

stop
@enduml
