@startuml
|Фазы|
|Пользователь|
start
:Пользователь открывает\nкаталог товаров;

|Система|
:Система отображает\nсписок товаров;

|Пользователь|
:Пользователь просматривает\nкаталог;

|Пользователь|
:Пользователь применяет\nфильтры;

|Система|
:Система обновляет\nсписок товаров;

|Пользователь|
:Пользователь выбирает\nтовар;

|Система|
:Система отображает\nдетальную информацию;

stop
@enduml
