@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    LifeLineBackgroundColor Black
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    ParticipantFontColor Black
}

skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "Прецедент 2. Авторизация администратора\nв системе" #White
participant "Администратор" as Admin #White
participant "Система" as System #White
participant "БД" as DB #White
end box

activate Admin #Black
activate System #Black
activate DB #Black

Admin -> System: Открытие окна авторизации
Admin -> System: Ввод данных для авторизации
System -> DB: Проверка данных
DB --> System: Авторизация администратора
System --> Admin: Переход в главное меню

deactivate DB
deactivate System
deactivate Admin

@enduml
