@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    LifeLineBackgroundColor White
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    ParticipantFontColor Black
}

actor Пользователь
participant "Система" as System
database "БД" as DB

Пользователь -> System: Открытие каталога товаров
System -> DB: Запрос списка товаров
DB --> System: Возврат списка товаров
System --> Пользователь: Отображение каталога
Пользователь -> System: Применение фильтров
System -> DB: Запрос отфильтрованных товаров
DB --> System: Возврат отфильтрованных данных
System --> Пользователь: Обновление списка товаров
Пользователь -> System: Выбор товара
System -> DB: Запрос детальной информации
DB --> System: Возврат информации о товаре
System --> Пользователь: Отображение деталей товара

@enduml
