@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    LifeLineBackgroundColor White
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    ParticipantFontColor Black
}

actor Пользователь
participant "Система" as System
database "БД" as DB

Пользователь -> System: Добавление товара в корзину
System -> DB: Сохранение товара в корзине
DB --> System: Подтверждение сохранения
System --> Пользователь: Обновление корзины
Пользователь -> System: Просмотр корзины
System -> DB: Запрос содержимого корзины
DB --> System: Возврат данных корзины
System --> Пользователь: Отображение корзины
Пользователь -> System: Изменение количества товара
System -> DB: Обновление количества
DB --> System: Подтверждение обновления
System --> Пользователь: Обновление итоговой суммы

@enduml
