@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    LifeLineBackgroundColor Black
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    ParticipantFontColor Black
}

skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "Прецедент 4. Просмотр каталога товаров" #White
participant "Администратор" as Admin #White
participant "Система" as System #White
participant "БД" as DB #White
end box

activate Admin #Black
activate System #Black
activate DB #Black

Admin -> System: Открытие раздела каталога
System -> DB: Запрос списка товаров
DB --> System: Возврат данных о товарах
System --> Admin: Отображение списка товаров
Admin -> System: Применение фильтров
System -> DB: Запрос отфильтрованных данных
DB --> System: Возврат отфильтрованных товаров
System --> Admin: Отображение результатов

deactivate DB
deactivate System
deactivate Admin

@enduml
