@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    LifeLineBackgroundColor Black
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    ParticipantFontColor Black
}

skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "Прецедент 1. Авторизация\nв системе" #White
participant "Пользователь" as User #White
participant "Система" as System #White
participant "БД" as DB #White
end box

User -> System: Открытие окна авторизации
activate System #Black

User -> System: Ввод данных для авторизации
System -> DB: Проверка данных
activate DB #Black

DB --> System: Авторизация пользователя
deactivate DB

System --> User: Переход в главное меню
deactivate System

@enduml
