@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    LifeLineBackgroundColor White
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    ParticipantFontColor Black
}

actor Администратор
participant "Система" as System
database "БД" as DB

Администратор -> System: Открытие раздела каталога
System -> DB: Запрос списка товаров
DB --> System: Возврат данных о товарах
System --> Администратор: Отображение списка товаров
Администратор -> System: Применение фильтров
System -> DB: Запрос отфильтрованных данных
DB --> System: Возврат отфильтрованных товаров
System --> Администратор: Отображение результатов

@enduml
