@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    LifeLineBackgroundColor White
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    ParticipantFontColor Black
}

actor Пользователь
participant "Система" as System
database "БД" as DB

Пользователь -> System: Нажатие кнопки "Выход"
System -> DB: Завершение сессии
DB --> System: Подтверждение
System --> Пользователь: Переход на страницу авторизации
System --> Пользователь: Подтверждение выхода

@enduml
