@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    LifeLineBackgroundColor Black
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    ParticipantFontColor Black
}

skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "Прецедент 12. Работа с корзиной" #White
participant "Пользователь" as User #White
participant "Система" as System #White
participant "БД" as DB #White
end box

activate User #Black
activate System #Black
activate DB #Black

User -> System: Добавление товара в корзину
System -> DB: Сохранение товара в корзине
DB --> System: Подтверждение сохранения
System --> User: Обновление корзины
User -> System: Просмотр корзины
System -> DB: Запрос содержимого корзины
DB --> System: Возврат данных корзины
System --> User: Отображение корзины
User -> System: Изменение количества товара
System -> DB: Обновление количества
DB --> System: Подтверждение обновления
System --> User: Обновление итоговой суммы

deactivate DB
deactivate System
deactivate User

@enduml
